export const SET_USER_AUTH_DATA = 'SET_USER_AUTH_DATA';
export const WIPE_USER_AUTH_DATA = 'WIPE_USER_AUTH_DATA';
export const SET_CURRENT_USER_DB_DATA = 'SET_CURRENT_USER_DB_DATA';
export const SET_CANDIDATE_USERS = 'SET_CANDIDATE_USERS';
export const ADD_CANDIDATE_USER = 'ADD_CANDIDATE_USER';
export const TOGGLE_MATCH = 'TOGGLE_MATCH';
